/**
 * PharmAI Export — Copy, PDF export, and share functionality
 * Uses html2pdf.js for PDF generation (loaded from CDN).
 */

// ─── Copy ───────────────────────────────────────────────────────────────────

/**
 * Copy the full chat session to clipboard as formatted text.
 */
function copyFullChat() {
  const session = getSession(activeSessionId);
  if (!session || session.messages.length === 0) {
    toast('No messages to copy', 'info');
    return;
  }

  const text = session.messages
    .filter(m => m.role !== 'system')
    .map(m => {
      const prefix = m.role === 'user' ? '👤 You' : '⚕️ PharmAI';
      return `${prefix}:\n${m.content}`;
    })
    .join('\n\n---\n\n');

  const header = `PharmAI Chat — ${session.title || 'Untitled'}\n${'='.repeat(40)}\n\n`;

  navigator.clipboard.writeText(header + text)
    .then(() => toast('Chat copied to clipboard', 'success'))
    .catch(() => toast('Copy failed', 'error'));
}

// ─── PDF Export ─────────────────────────────────────────────────────────────

/**
 * Export current chat session as a PDF document.
 * Uses html2pdf.js library loaded from CDN.
 *
 * WHY from CDN: Keeps the codebase lightweight and avoids
 * bundling a heavy library. The CDN is reliable for hackathon demos.
 */
async function exportChatPDF() {
  const session = getSession(activeSessionId);
  if (!session || session.messages.length === 0) {
    toast('No messages to export', 'info');
    return;
  }

  // Ensure html2pdf is loaded
  if (typeof html2pdf === 'undefined') {
    toast('Loading PDF library...', 'info');
    try {
      await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js');
    } catch {
      toast('Could not load PDF library', 'error');
      return;
    }
  }

  // Build HTML content for PDF
  const htmlContent = buildPdfContent(session);

  // Create temporary container
  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = htmlContent;
  tempDiv.style.position = 'absolute';
  tempDiv.style.left = '-9999px';
  document.body.appendChild(tempDiv);

  try {
    await html2pdf()
      .set({
        margin: [15, 15, 15, 15],
        filename: `PharmAI-${session.title || 'Chat'}-${new Date().toISOString().slice(0, 10)}.pdf`,
        image: { type: 'jpeg', quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      })
      .from(tempDiv)
      .save();

    toast('PDF exported!', 'success');
  } catch (err) {
    toast('PDF export failed', 'error');
    console.error('PDF error:', err);
  }

  document.body.removeChild(tempDiv);
}

function buildPdfContent(session) {
  const date = new Date(session.createdAt).toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  let html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; padding: 20px;">
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #0D9488; margin: 0;">⚕️ PharmAI Report</h1>
        <p style="color: #666; margin: 5px 0;">${escapeHtml(session.title || 'Untitled Chat')}</p>
        <p style="color: #999; font-size: 12px;">${date}</p>
      </div>
      <hr style="border: 1px solid #E5E7EB;">
  `;

  for (const msg of session.messages) {
    if (msg.role === 'system') continue;

    const isUser = msg.role === 'user';
    const label = isUser ? '👤 You' : '⚕️ PharmAI';
    const bgColor = isUser ? '#F0FDFA' : '#FFFFFF';
    const borderColor = isUser ? '#0D9488' : '#E5E7EB';

    html += `
      <div style="margin: 15px 0; padding: 12px; border-left: 3px solid ${borderColor}; background: ${bgColor}; border-radius: 4px;">
        <strong style="color: ${isUser ? '#0D9488' : '#374151'};">${label}</strong>
        <div style="margin-top: 8px; line-height: 1.6;">${isUser ? escapeHtml(msg.content) : renderMd(msg.content)}</div>
      </div>
    `;
  }

  html += `
      <hr style="border: 1px solid #E5E7EB; margin-top: 30px;">
      <p style="text-align: center; color: #999; font-size: 10px;">
        Generated by PharmAI — AI-Powered Pharmaceutical Intelligence<br>
        This report is AI-generated and should not replace professional medical advice.
      </p>
    </div>
  `;

  return html;
}

// ─── Share ──────────────────────────────────────────────────────────────────

/**
 * Share current chat via Web Share API (mobile) or copy link.
 */
async function shareChat() {
  const session = getSession(activeSessionId);
  if (!session) {
    toast('No active chat to share', 'info');
    return;
  }

  const shareData = {
    title: `PharmAI: ${session.title || 'Chat'}`,
    text: session.messages
      .filter(m => m.role !== 'system')
      .slice(0, 3)
      .map(m => m.content.slice(0, 100))
      .join('\n'),
    url: window.location.href,
  };

  if (navigator.share) {
    try {
      await navigator.share(shareData);
    } catch (err) {
      if (err.name !== 'AbortError') toast('Share failed', 'error');
    }
  } else {
    // Fallback: copy text to clipboard
    copyFullChat();
  }
}

// ─── Utility ────────────────────────────────────────────────────────────────

function loadScript(src) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = src;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
}
